[program:comfyui]
command=/venv/main/bin/python /workspace/ComfyUI/main.py --listen 127.0.0.1 --port 18188
directory=/workspace/ComfyUI
autostart=true
autorestart=true
stderr_logfile=/var/log/portal/comfyui.log
stdout_logfile=/var/log/portal/comfyui.log
